# Mulong Luo
# muluo@ucsd.edu
#

FROM ubuntu:14.04
MAINTAINER Mulong Luo <muluo@ucsd.edu>
#RUN apt-get update && apt-get install -y ruby ruby-dev
#RUN gem install sinatra
VOLUME ["/data"]
ADD string.txt /data/
ADD string1.txt /data/
ADD demo/* /data/
